openSUSE/obs-docu

README
Old adress still works because it forwards to the new one. Anyways I
think the correct one should be used.
=> Update repo URL

xml/obs_build_config.xml
``PublishFilter`` documentation, correctly say that it filters out, not in.
Fixes #30.
=> Follow-up to cf87ebc, negate statement for PublishFilter

xml/obs_build_job_constraints.xml
Basic documentation of the new constraint handling. The new sections starting at page 87. 
Full PDF attached. 
[obs-reference-guide_color_en.pdf](https://github.com/openSUSE/obs-docu/files/611106/obs-reference-guide_color_en.pdf)
@adrianschroeter @mlschroe please review.
=> added basic docu for new constraint handling

xml/obs_build_job_constraints.xml
added documentation for constraints checking with osc.
[obs-reference-guide_color_en.pdf](https://github.com/openSUSE/obs-docu/files/680818/obs-reference-guide_color_en.pdf)
@adrianschroeter please have a look
=> documentation for osc checkconstraints/workerinfo

xml/obs_glossary.xml
osc - the nice and little tool everybody is "just using" which comes from here https://github.com/openSUSE/osc - is just used in this documentation but never explained - so i added it to the glossary, that people can lookup what osc means, where it lives and where its own repo is.
makes things less complicated for new users to OBS which do not know about everything.
Maybe @lethliel want to add osc2 to glossary and OBS docu, as soon as its ready.
@hennevogel @Ana06 maybe review this :sunglasses:
=> explained osc in Glossary - as it was nowhere before

xml/obs_ag_user_management.xml
This script mainly useful when setting up OBS for LDAP.
=> Document script that allows to give admin permissions to users

xml/obs_ag_installation_and_configuration.xml
* Mention the packages that has to be installed and services that need to be started.
* Fix path to AWS configuration file
* Drop section about the enceladus script we use, since we don't want or expect users to
change it's default configuration.
=> Update admin guide for OBS cloud upload configuration

xml/obs_ag_installation_and_configuration.xml
Having a wrong system time on the cloud uploader instance can lead
to failures during the upload.
https://github.com/openSUSE/open-build-service/issues/4633
=> Document cloud upload issue related to system time

xml/art-obs-beginners-guide.xml, xml/entity-decl.ent
- Changed the name of the package to the name of the git project.
- Changed link to the reference spec to point to the one on OBS.
Note: I wasn't able to run daps to validate these changes, it complained about not finding the stylesheet. I assume this is because they're not available on Fedora. I'm going to set up a VM and see if it'll work there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/opensuse/obs-docu/99)
=> Minor documentation update.

xml/obs_source_service.xml
Fix a typo and an incorrect remark resulting from confusion caused by https://github.com/openSUSE/osc/issues/282.
=> fix serveronly mode documentation

xml/obs_build_config.xml
I was unable to configure this feature properly until I asked the mailing list for clarification.
So I rephrased the text a bit, added an example combining splitdebug with a repo format and described the result.
I did not build the documentation because whatever daps is, I don't have it in my distribution.
=> clarify splitdebug usage in project config

xml/obs_multibuild.xml
The spec-file has to include the repository name before the
file-extension directly behind the package name with a -
This should be the line from bs_srcserver source:
@files = grep {/^\Q$packid-$repoid\E/i} @files if @files > 1;
=> Fixed naming for repo-specific spec-files in obs_multibuild

README.md
There wasn't any clue about deployment in this project. We add here
some instructions and link to «obs-landing» for the last steps to
follow.
Fixes #121
=> Add instructions to deploy documentation

README.md
Using the daps example as shown in README.md results in [error](https://github.com/openSUSE/obs-docu/issues/139) because the file DC-obs-beginners-guide doesn't exist anymore.
Changing it to DC-obs-user-guide, which exists.
=> Change example for building books since DC-obs-beginners-guide doesn't exist anymore.

xml/obs_ag_installation_and_configuration.xml
The text appears to mean 'systemctl enable' the services before starting
them.
=> Admin Guide: enable services before start

README.md
The books that were merged into User Guide are not mentioned in README
anymore.
=> Remove references to non-existent books in README

xml/obs_source_service.xml
services mode=disabled exists since the beginning of the time
(of OBS services)
=> remove invalid statement

.github/workflows/ci.yaml
This will add a Github Workflow which:
* builds the container
* validates the xml
* generates HTML
* uploads HTML as an artifact for easy inspection, so you don't need to build locally to review a PR
An example run can be found in my fork:
https://github.com/perlpunk/obs-docu/actions/runs/518327457
=> Add Github Workflow

xml/obs_basic_workflow.xml
This PR updates the link to the RPM packaging guide. The guide has been permanently moved to https://rpm-packaging-guide.github.io
=> Update link to the RPM packaging guide

xml/book-obs-user-guide.xml, xml/obs_build_containers.xml, xml/obs_package_formats.xml
The user guide does not mention the container registry at all, especially that you can use the published gpg signatures with podman for verification. This PR adds a rudimentary guide how to use this feature.
cc @tomschr @adrianschroeter
=> Add chapter about the published container registry 

xml/obs_scm_ci_workflow_integration.xml
Here's a preview of the changes:
You can also review the documentation by checking out this branch and running:
```
docker-compose run obs-docu daps -vv -d DC-obs-all html
```
Once the command is done, open `build/obs-all/html/obs-all/cha.obs.scm_ci_workflow_integration.html` with a web browser.
=> Document tag_push for event filter in SCM/CI integration

xml/obs_scm_ci_workflow_integration.xml
For the recent changes in the SCM/CI integration with supporting push events for tags.
First:
Second:
Third:
You can also review the documentation by checking out this branch and running:
```
docker-compose run obs-docu daps -vv -d DC-obs-all html
```
Once the command is done, open `build/obs-all/html/obs-all/cha.obs.scm_ci_workflow_integration.html` with a web browser.
=> Document package names with push events for tags

xml/obs_scm_ci_workflow_integration.xml
Here's how you can test this locally:
- `docker-compose run --rm obs-docu daps -vv -d DC-obs-all html`
- `your_favorite_browser build/obs-all/html/obs-all/cha.obs.scm_ci_workflow_integration.html`
Preview:
=> Clarify how the event changes the configure_repositories step

xml/obs_scm_ci_workflow_integration.xml
This includes the usual step documentation in addition to a use-case.
To review the changes locally:
1. `docker-compose run --rm obs-docu daps -vv -d DC-obs-all html`
2. `firefox/other_browser build/obs-all/html/obs-all/cha.obs.scm_ci_workflow_integration.html`
=> Document set_flags step

.github/workflows/deploy-to-obs-landing.yaml
This GitHub action automatically builds the obs documentation and pushes the newly generated doc books to the obs-landing repository using a GitHub deployment key (basically an ssh key, that has only permission for a single repository).
It basically does the same that we did manually in the past https://github.com/openSUSE/obs-docu#update-documentation
See test runs on my fork https://github.com/krauselukas/obs-docu/actions/runs/1986616461
TODO:
=> Use github actions to deploy obs-docs on obs-landing

xml/obs_scm_ci_workflow_integration.xml
We already got feedback from users thinking that they could pass an array of events in the event filter.
To review the changes locally:
1. `docker-compose run --rm obs-docu daps -vv -d DC-obs-all html`
2. `firefox/other_browser build/obs-all/html/obs-all/cha.obs.scm_ci_workflow_integration.html`
=> Clarify how event filters have to be defined

.github/workflows/deploy-to-obs-landing.yaml
Before switching to the daps2docker CLI, the github action used
an docker image which worked with an older version of DAPS (2.*.*
instead of 3.2.0).
This led to several little differences in the built docs, like
having `http` links instead of `https`. It is easier to rely on
the CLI tool in the github action over manually executing all
the necessary steps.
See test runs on my fork https://github.com/krauselukas/obs-docu/actions/runs/2035669936
=> Use daps2docker in obs-docs deployment github action

xml/obs_scm_ci_workflow_integration.xml
To test this locally:
1. Pull the changes from this PR, then run `daps2docker .`
2. Open the generated user guide in your favorite browser: `firefox /tmp/daps2docker-SXo2tVAc/obs-user-guide/html/book.obs-user/cha.obs.scm_ci_workflow_integration.html` (the string after `daps2-docker-` will be different).
=> Document trigger_services step for SCM/CI Workflow Integration

xml/obs_scm_ci_workflow_integration.xml
To test this locally:
1. Pull the changes from this PR, then run `daps2docker .`
2. Open the generated user guide in your favorite browser: `firefox /tmp/daps2docker-SXo2tVAc/obs-user-guide/html/book.obs-user/cha.obs.scm_ci_workflow_integration.html` (the string after `daps2-docker-` will be different).
=> Add a use case with push events for tags

xml/obs_scm_ci_workflow_integration.xml
Those aren't needed anymore since we improved the error messages in https://github.com/openSUSE/open-build-service/pull/12412 instead of having a table in the user documentation for this.
=> Remove outdated error messages from errors table in SCM/CI integration

xml/obs_supported_formats.xml
This prevents misunderstandings like https://github.com/openSUSE/obs-build/issues/846
=> Clarify ArchExclusiveLine and ArchExcludedLine

xml/obs_ag_source_service.xml, xml/obs_source_service.xml
The update_source service is long obsolete and no package for this
service currently exists in openSUSE:Factory.
=> Drop references to obsolete update_source service

xml/obs_build_config.xml, xml/obs_build_containers.xml, xml/obs_package_formats.xml, xml/obs_supported_formats.xml
https://github.com/openSUSE/obs-build/pull/861
https://github.com/openSUSE/open-build-service/pull/12972
Note that I haven't tested that this builds and displays, as (without any changes) daps fails for me on Debian testing:
```
$ daps -d DC-obs-user-guide html
Could not resolve URN "urn:x-suse:xslt:profiling:docbook51-profile.xsl" with xmlcatalog via catalog file "/etc/xml/catalog"
/usr/share/daps/make/profiling.mk:47: *** .  Stop.
```
=> Add initial documentation and example for mkosi

xml/obs_scm_ci_workflow_integration.xml
After months of tracking the usage of the SCM/CI integration elements, we realized the `architectures` and `repositories` filters have never been used. So we conclude those filters are not helpful for our customers and we get rid of them.
We removed some sections in the user documentation and adapt others. See the screenshots comparing them:
=> Remove unused filters 'architectures' and 'repositories'

xml/obs_scm_ci_workflow_integration.xml
The section 'SCM/CI Workflow Integration' is not a beta feature anymore.
=> Drop [Beta Feature] label from SCM/CI Integration

xml/obs_scm_ci_workflow_integration.xml
To test this locally:
1. Pull the changes from this PR, then run `daps2docker .`
2. Open the generated user guide in your favorite browser: `firefox /tmp/daps2docker-SXo2tVAc/obs-user-guide/html/book.obs-user/cha.obs.scm_ci_workflow_integration.html` (the string after `daps2-docker-` will be different).
**DO NOT MERGE**: Wait for https://github.com/openSUSE/open-build-service/pull/13498 to be merged and deployed.
=> Document placeholder variables for SCM/CI Integration

xml/obs_scm_ci_workflow_integration.xml
Related to https://github.com/openSUSE/open-build-service/pull/13841
=> Add note about branches filter not supporting tag push events

xml/obs_best_practice_webui_usage.xml
Follow-up  of #278
The image used in the commented XML was removed on a previous commit, as Daps considered it was not in use.
The XML has been commented on for 6 years now, it's safe to remove it.
=> Remove commented XML that added inline image

xml/obs_best_practice_integrate_scm_sources.xml
Better highlight that avoiding tarballs means not having source code bundled with RPM source packages.
=> Clarify use of SCM sources

xml/obs_glossary.xml
The Glossary lacks a term explaining what an API is, and while we're at it, add a link to our new API Docs site.
=> Add a link into a new chapter for the revamped API docs

xml/entity-decl.ent
=> OBS caches download location is changed to `/var/tmp/oscbuild-packagecache`

xml/art-obs-beginners-guide.xml
The description in the document no longer conforms to the current version of https://build.opensuse.org/ for the naming and location of the Home Project link.
It is now in a left menubar under Places and named Your Home Project.
I have validated the change with 
`daps2docker DC-obs-user-guide validate` and
`rm -rf /tmp/daps2docker-*; daps2docker DC-obs-user-guide html; xdg-open /tmp/daps2docker-*/obs-user-guide/html/book.obs-user/index.html`
=> Location and minor change for Home Project link

xml/obs_osc.xml
This PR adds documentation for `cafile`/`capath` options in `.oscrc`
=> osc: Add documentation for cafile/capath

xml/obs_ag_security_concepts.xml
Proposing some small typo updates to the "Signature Handling" section.
=> Small typo updates to the Security Concepts page

DC-obs-user-guide
(Apparently, this used to be called the "Reference Guide", but that must have been a long time ago?)
=> DC-obs-user-guide: fix title so it refers to "User Guide"

xml/obs_ag_installation_and_configuration.xml
The unit file to be enabled/started for the API is "obs-api-support.target", not "obsapidelayed.service" anymore.
Fixes: https://github.com/openSUSE/obs-docu/issues/297
=> admin guide/API Configuration: fix name of systemd unit file

xml/obs_ag_publish_hooks.xml
Variable definition was broken and the destination path has to be created on first run.
=> Fixed example Scripts for publisher hook

xml/obs_scm_bridge.xml
changed defaults and changed recommendations
=> Update scmsync documentation

xml/obs_build_config.xml
Following 1937d463677ba3b8bec77d0564ce774018615075 we had some redundant text regarding repository types. This commit eliminates it.
=> obs_build_config: eliminate redundant text

xml/obs_ag_installation_and_configuration.xml
1024 bits for RSA keys is probably too little these days (it is still allowed using LEGACY crypto policy).
Fixes: https://github.com/openSUSE/obs-docu/issues/222
=> obs_ag_installation_and_configuration: use higher RSA bits

xml/obs_ag_tools.xml
Let's refer the reader to osc instead of copying blocks of text from "osc foo --help" into the book.
=> obs_ag_tools: refrain from dumping "osc foo --help"

DC-obs-admin-guide, DC-obs-all, DC-obs-user-guide, xml/obs_build_config.xml
Nesting screen inside para is a violation of the GeekoDoc XML schema and will cause the CI build to fail if/when we (eventually) switch to GeekoDoc.
=> obs_build_config: refrain from nesting screen inside para

DC-obs-admin-guide, DC-obs-all, DC-obs-user-guide
It came to my attention that we were using an obsolete set of stylesheets. Use the current version instead.
=> DC: migrate to the latest stylesheets

xml/art-obs-beginners-guide.xml
Explain how to supersede an SR, as requested in https://github.com/openSUSE/obs-docu/issues/236
=> art-obs-beginners-guide: explain how to supersede an SR

xml/obs_build_config.xml
OBS still knows the old strings, but they were in no official release and we try to keep the documentation not confusing. Therefore not mention the old strings anymore.
=> Adapt to renamed publishflags

xml/book-obs-admin-guide.xml, xml/book-obs-user-guide.xml, xml/obs_ag_high_level_overview.xml
The current "Administration" chapter in the "Reference" section of the User Guide contains admin-focused content and therefore belongs in the Admin Guide.
Moreover, the Admin Guide is missing a "High-level Overview" of the Build Service, and this chapter provides it.
Fixes: https://github.com/openSUSE/obs-docu/issues/366
=> Move UG: Administration to AG: High-level Overview

xml/obs_basic_workflow.xml
This subsection had been disabled, but there is no good reason why not to start a discussion about it by publishing it. Without publishing, one has to read the obs-docu source code to even know the subsection exists.
=> obs_basic_workflow.xml: render/publish "Aggregating a package" subsection

xml/obs_build_constraints.xml
Fixes: https://github.com/openSUSE/obs-docu/issues/122
=> obs_build_constraints.xml: drop double-quotes from unit= values

xml/art-obs-beginners-guide.xml
The word "project" has a special meaning in the OBS context, so let's be careful when using it in the OBS documentation.
=> art-obs-beginners-guide.xml: address terminology confusion

xml/obs_ag_message_bus.xml
`container.published` and `relationship.create` were missing
=> Add missing routing keys

xml/art-obs-beginners-guide.xml, xml/obs_basic_workflow.xml
Fixes: https://github.com/openSUSE/obs-docu/issues/392
=> art-obs-beginners-guide,obs_basic_workflow: Reduce duplication

xml/obs_scm_ci_workflow_integration.xml
User documentation for LABELS filter introduced in https://github.com/openSUSE/open-build-service/pull/17373.
Please only merge after [this PR](https://github.com/openSUSE/open-build-service/pull/17373) is deployed.
=> Add user documentation for labels filter

xml/obs_build_config.xml
The prjconf keyword is "Required", not "Require".
=> obs_build_config.xml: fix references to Required prjconf keyword

.github/workflows/deploy-to-obs-landing.yaml
Currently `build-obs-docs` job fails on `build html` step with the error `mv: cannot move '/tmp/daps2docker-*/...' to '../obs-landing/help/manuals/obs-admin-guide': Permission denied`. 
This pr attempts to resolve this error.
=> Change mv to cp to avoid a permission denied error

xml/art-obs-beginners-guide.xml, xml/obs_osc.xml
The osc package only recommends packages people usually need for working.
Fixes #424
=> Fix zypper install osc suggestions

xml/obs_build_containers.xml, xml/obs_package_formats.xml
OBS can now sign mkosi built images, and build them from git,
so expand the documentation.
=> xml: expand mkosi documentation for latest OBS features
