openSUSE/obs-docu

- .gitignore
- xml/obs_concepts.xml
- xml/obs_concepts_dod.xml
@mlschroe, @adrianschroeter - Please review, don`t pull !
> Documentation of DoD

- xml/obs_source_service.xml
Improve English and clarify network access restrictions in buildtime mode.
> source services: clarify section on "buildtime mode"

- xml/obs_ag_user_management.xml
BTW, I fixed one sentence related to Kerberos options.yml
> Drop LDAP account edition support

- xml/obs_glossary.xml
Taken from the Docker Quick Start
> Glossary: define Docker

- xml/obs_ag_installation_and_configuration.xml
There is no need nor reason to add two emphasis tags to a text.
> Fix doublication of emphasis tags

- xml/obs_ag_source_service.xml
- xml/obs_source_service.xml
> fixed serveronly entry

- xml/obs_ag_overview_filesystem.xml
It's now possible to distinguish configuration options by Rails
environment.
https://github.com/openSUSE/open-build-service/issues/4075
> Document recent change of options.yml

- .travis.yml
> Validate books in travis

- README.md
Indent correctly the quoted code and so fix the numbering of the ordered list.
> Fix ordered list

- xml/obs_best_practice_staging_workflow.xml
I described the table content a little bit
> Describe content of the staging workflow table

- xml/book-obs-best-practices.xml
- xml/obs_ag_source_service.xml
- xml/obs_best_practice_integrate_scm_sources.xml
- xml/obs_source_service.xml
Some important hints how to work with SCM sources.
I know that the book build is broken, but I have no clue why, since the reported false string ("format") does not exist in the file.
Any help is welcome:) Either a hint or just fix it yourself, thanks!
> Scm sources

- xml/obs_ag_user_management.xml
> Add gravatars for groups to administration guide

- xml/art-obs-beginners-guide.xml
I went through the guide this week and included some fixes and improvements I came across in this PR.
> Revision of the Beginner's Guide

- xml/obs_ag_dispatch_priority.xml
Signed-off-by: Olaf Hering <olaf@aepfle.de>
> fix grammar in Dispatch Priorities

- xml/obs_source_service.xml
* enable and fix the table again
* introduce "manual" mode
> fix some documentation regarding service modes

- xml/osc_building.xml
> Container specials

- xml/obs_ag_security_concepts.xml
> fix some typos in security section (admin guide)

- xml/obs_ag_security_concepts.xml
Do not merge yet, needs some more reviews and extensions.
> initial description of signature key handling

- xml/obs_ag_administration.xml
@bugfinder @lethliel not considered to be final, feel free to comment, extend, fix ...
> very first stub for backup chapter

- xml/obs_ag_message_bus.xml
cc @hennevogel @adrianschroeter
> Add missing rabbitmq messages

- xml/obs_build_config.xml
This squashes the existing three commits from #150 and adds another one on top to clarify. @adrianschroeter / @dmarcoux  / @sjamgade , Do you have opinions on this?
> Edited version of sjamgade's ccache doc (PR #150)

- xml/obs_architecture.xml
An underscore prefix is required
> fixed dispatch priorities adjust API endpoint

- xml/obs_build_config.xml
~~@adrianschroeter Unfortunately I have no idea what this flag actually does~~
@adrianschroeter I've tried to document the flag to the best of my knowledge.
cc @Vogtinator
> Add documentation of the obsgendiff buildflag

- xml/obs_build_job_constraints.xml
was obviously copied from further up
> Fix copy-pasto issue

- xml/obs_source_service.xml
> Fix broken footnote

- xml/book-obs-user-guide.xml
- xml/obs_scm_ci_workflow_integration.xml
You can review the documentation checking out this branch and then running:
```
docker-compose run obs-docu daps -vv -d DC-obs-all html
```
And then opening `build/obs-all/html/obs-all/cha.obs.scm_ci_workflow_integration.html` with a web browser.
> Add SCM/CI Workflow Integration chapter

- xml/obs_scm_ci_workflow_integration.xml
I found some mistakes on https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html
> Fix YAML syntax in SCM/CI Workflow docs

- xml/obs_scm_ci_workflow_integration.xml
Preview of the new note about multibuild flavors:
> Improvements for the SCM/CI Integration

- DC-obs-admin-guide
- DC-obs-all
- DC-obs-user-guide
> Fast forward docbook stylesheets 10 years

- .github/workflows/deploy-to-obs-landing.yaml
git commit -a will only add known files.
> Also commit new files in the deploy job

- .github/workflows/ci.yaml
Something I've noticed following the merge of #203.
> Remove unneeded lines .github/workflows/ci.yaml

- xml/obs_binary_tracking.xml
The provided examples are already updated in the new API reference documentation.
**Before:**
**After:**
> Link to the API documentation, for binary search

- xml/obs_request_and_review_system.xml
Just a few things I noticed while reading the docs…
> Minor grammatical improvements

- xml/obs_scm_ci_workflow_integration.xml
Adding a use case for configuration url and placeholder variable features together, showing the possibilities of it.
> Use case for scm/ci workflow with configuration url and placeholder variables

- xml/obs_scm_ci_workflow_integration.xml
See https://github.com/openSUSE/open-build-service/pull/14437 for details.
Also document the service limitation of link_package.
> Document add_repositories for branch package step

- .github/workflows/deploy-to-obs-landing.yaml
Makes it more obvious which one has failed in case of failure.
> Split build task to fix

- xml/obs_scm_ci_workflow_integration.xml
We document which SCM events we support and we also document what each step does for the different SCM events.
> Add table to document which event on the SCM will trigger which actions on OBS

- xml/obs_scm_ci_workflow_integration.xml
> Add submit request step to SCM/CI

- xml/obs_scheduling_and_dispatching.xml
- xml/obs_supported_formats.xml
Also writing a little bit regarding build counter syncing at all. Still much missing, but it is a start ...
> Document bcntsynctag source parsing support.

- xml/obs_supported_formats.xml
See https://github.com/openSUSE/obs-build/commit/1a8b6a8889dc63c45776baacbcf60eca6a353226
> Add the hint that buildname and buildversion need to be paired

- xml/obs_ag_installation_and_configuration.xml
Fixes: https://github.com/openSUSE/obs-docu/issues/296
> admin: rework Back-end Installation section

- xml/obs_ag_installation_and_configuration.xml
Fixes: https://github.com/openSUSE/obs-docu/issues/319
> admin/Cloud Upload Setup: eliminate redundant subsection heading

- xml/obs_build_config.xml
> add nodisturl buildflag docu

- xml/obs_scm_ci_workflow_integration.xml
This corresponds with the two uses of the Octokit library in OBS:
- [YAML Downloader](https://github.com/openSUSE/open-build-service/blob/7626f51daedcd2fb7fbb0942e588b269e3f27c11/src/api/app/services/workflows/yaml_downloader.rb#L39)
- [Status Reporter](https://github.com/openSUSE/open-build-service/blob/7626f51daedcd2fb7fbb0942e588b269e3f27c11/src/api/app/services/github_status_reporter.rb#L18-L21)
> Add information about github fine-grained tokens

- xml/MAIN-obs.xml
Makes the "Report bug icon show up in both guides
> Adding docmanager section for Bugreports

- xml/obs_admin_components.xml
- xml/obs_ag_administration.xml
- xml/obs_architecture.xml
- xml/obs_best_practice_upstream.xml
- xml/obs_best_practice_webui_usage.xml
- xml/obs_build_config.xml
- xml/obs_build_constraints.xml
- xml/obs_build_containers.xml
- xml/obs_maintenance_setup.xml
- xml/obs_moderation.xml
- xml/obs_notifications.xml
- xml/obs_scm_bridge.xml
- xml/obs_scm_ci_workflow_integration.xml
- xml/obs_source_management.xml
- xml/obs_source_service.xml
- xml/schemas.xml
Fixes Geekodoc validation errors (except for IDs)
> Fixed geekodoc validation issues

- DC-obs-admin-guide
- DC-obs-user-guide
- xml/MAIN-obs.xml
> Disable SUSE Logo and share links

- xml/obs_basic_workflow.xml
Fixes: https://github.com/openSUSE/obs-docu/issues/236
> obs_basic_workflow: explain how to "move" a file

- xml/obs_concepts.xml
Fixes: https://github.com/openSUSE/obs-docu/issues/372
> obs_concepts.xml: link to Build Configuration chapter

- .github/workflows/deploy-to-obs-landing.yaml
> Copy files recursively in build html step

- xml/obs_supported_formats.xml
Also harmonise the writing style of all tags.
> Add missing OBS specific tags of rpm spec file recipe
